### ISSUE TITLE
campaign_twitter_ids not showing up in the API

### ISSUE THREAD

**Issue by nickom** [propublica/sunlight-congress#478]
This field seems to be missing from the API calls I try. Here's the results using the example of Sen. Sherrod Brown ([the one used in the documentation](https://sunlightlabs.github.io/congress/legislators.html)):

Call:
congress.api.sunlightfoundation.com/legislators?bioguide_id=B000944&apikey=[APIKEY]

Response body:
{
    "results": [
        {
            "bioguide_id": "B000944",
            "birthday": "1952-11-09",
            "chamber": "senate",
            "contact_form": "http://www.brown.senate.gov/contact",
            "crp_id": "N00003535",
            "district": null,
            "facebook_id": null,
            "fax": "202-228-6321",
            "fec_ids": [
                "H2OH13033",
                "S6OH00163"
            ],
            "first_name": "Sherrod",
            "gender": "M",
            "govtrack_id": "400050",
            "icpsr_id": 29389,
            "in_office": true,
            "last_name": "Brown",
            "lis_id": "S307",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "oc_email": "Sen.Brown@opencongress.org",
            "ocd_id": "ocd-division/country:us/state:oh",
            "office": "713 Hart Senate Office Building",
            "party": "D",
            "phone": "202-224-2315",
            "senate_class": 1,
            "state": "OH",
            "state_name": "Ohio",
            "state_rank": "senior",
            "term_end": "2019-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "00136",
            "title": "Sen",
            "twitter_id": "SenSherrodBrown",
            "votesmart_id": 27018,
            "website": "http://www.brown.senate.gov",
            "youtube_id": "SherrodBrownOhio"
        }
    ],
    "count": 1,
    "page": {
        "count": 1,
        "per_page": 20,
        "page": 1
    }
}

**Comment by handlers** [comment]
Ah yes -- I closed it because the system was working as expected and didn't interpret it as a functionality change request at the time. Created a new ticket here #491.

**Comment by nickom** [comment]
Got it, thanks!
