### ISSUE TITLE
Some bills have null responses for search endpoint (but not bills endpoint)

### ISSUE THREAD

**Issue by dwillis** [propublica/sunlight-congress#538]
Example: https://congress.api.sunlightfoundation.com/bills/search?per_page=50&page=1&apikey=5ddd9b522b204fb599123fc03b6d8745&congress=114&fields=*,summary_short&bill_id=hr22-114

**Comment by markdboyd** [comment]
I have a different example, but I think the same fundamental problem: some filter fields don't seem to work correctly for the bills/search/ endpoint that do work for the bills/ endpoint.

In my case, I have noticed that when filtering for bills that are awaiting signature, I do get a response from the bills/ endpoint:

https://congress.api.sunlightfoundation.com/bills?apikey=<API_KEY>&history.awaiting_signature=true&congress=114

But not the bills/search/ endpoint:

https://congress.api.sunlightfoundation.com/bills/search?apikey=<API_KEY>&congress=114&history.awaiting_signature=true
