### ISSUE TITLE
API Key registration page not found

### ISSUE THREAD

**Issue by dclemons2015** [propublica/sunlight-congress#540]
This link is down http://services.sunlightlabs.com/accounts/register/. I cannot register for an access key.

**Comment by whob13** [comment]
+1

**Comment by bniedermeyer** [comment]
@dclemons2015 Per [this article](https://www.propublica.org/nerds/item/sunlight-labs-takeover-update) that functionality has been turned off until they finish the migration to ProPublica. For now you can use the API without needing a key.
