### ISSUE TITLE
Plans for including local office information?

### ISSUE THREAD

**Issue by ysimidjiyski** [propublica/sunlight-congress#544]
Hi folks,

Are there any plans to include information about local offices in the Sunlight API?  According to the docs at https://sunlightlabs.github.io/congress/legislators.html (which I recognize may be out of date by now), we receive a single "location" field with phone numbers and office addresses.  The phone numbers, at least, all appear to go to the DC offices right now.  Directing my users to contact their Senator's national office is all well and good, but I would rather direct people to their local offices first.

I know you folks just took this project over from the sunlight team (thank you so much!), so I'm not sure if you're taking feature requests right now.  Frankly, this request has almost certainly been considered and rejected for one reason or another in the past, though I'm not seeing it anywhere under closed issues (maybe I missed it?).  Still, I thought this was worth opening and getting a heads up about your plans before I go and look for this data elsewhere or compile it on my own.

**Comment by halffullheart** [comment]
I’m also interested in the same data, in particular phone numbers for local offices. Does anyone know of an existing data source for this?

**Comment by halffullheart** [comment]
Update: I found [this data source](https://github.com/TheWalkers/congress-legislators/blob/master/legislators-district-offices.yaml) for district offices. (@ysimidjiyski you might be interested)

**Comment by ysimidjiyski** [comment]
Thanks @halffullheart!  There is now a project that uses the yaml you linked to in order to provide an API to access the local office data.  See http://www.phoneyourrep.com and https://github.com/msimonborg/phone-your-rep-api

**Comment by cldwalker** [comment]
Callers are consistently running into busy signals and full voicemail boxes at the federal level. Adding local numbers would be super useful to the public.
@dwillis I could help w/ this if you could provide a checklist of things that need to be done here including any coordination with https://github.com/unitedstates/congress-legislators

**Comment by dwillis** [comment]
Yeah, there's an effort underway at the United States repo (https://github.com/unitedstates/congress-legislators/issues/343) to address this, and if there's a way to keep that data up-to-date we'd include it.

**Comment by cldwalker** [comment]
Ah, missed that. If congress-legislators won't take @TheWalkers data, would you be willing to incorporate it as is or with additional polish? https://github.com/TheWalkers/congress-turk is well documented and is released into the public domain

**Comment by dwillis** [comment]
My preference would be to have it in congress-legislators, since we use that, too, but yes, if that's not an option we'll look at it.

**Comment by konklone** [comment]
I would very much like to take @TheWalkers data into congress-legislators. Let's find a way to do that. I think closing out the remaining checkboxes in https://github.com/unitedstates/congress-legislators/issues/375 will calm things down, as will demonstrating that the repo has several active ongoing maintainers.
