### ISSUE TITLE
Boundary server URL

### ISSUE THREAD

**Issue by cwoloszynski** [propublica/sunlight-congress#547]
I am trying to get this working on my server to try it out and I am running into a problem not being able to look up a congressional rep by lat/long.  It looks like it is looking for location: information from the config.yml.    But the example one does not provide any insight into where I should look for a service that supports the required API.  

Can you help me with any pointers for that data/service?

**Comment by dwillis** [comment]
@cwoloszynski one solution would be to run your own boundary service, using either the [original Sunlight codebase](https://github.com/propublica/pentagon) or the newer one used by [Represent North](https://github.com/opennorth/represent-boundaries).
