### ISSUE TITLE
no recent bills?

### ISSUE THREAD

**Issue by troverman** [propublica/sunlight-congress#549]
I've noticed the bills api is currently almost a month outdated. This is occurring when calling https://congress.api.sunlightfoundation.com/bills. Are we working on a solution? 

Thanks for your response!

**Comment by dwillis** [comment]
@troverman yes, we're working on a solution. sorry for the late response.

**Comment by troverman** [comment]
@dwillis in the interitum we wrote a solution referencing the propublica bills api. moving forward, do you anticipate either one receiving more attention-maintenance etc. or that they will both be equally supported. 

Thanks for your response!

**Comment by dwillis** [comment]
@troverman Going forward the Sunlight Congress API will be retired sometime this summer, per our [update here](https://www.propublica.org/nerds/item/congress-api-update)

**Comment by troverman** [comment]
@dwillis thanks for the update! we will plan accordingly.
