### ISSUE TITLE
Bills and senate hearings not up to date

### ISSUE THREAD

**Issue by cynbreck** [propublica/sunlight-congress#550]
Neither the bills data nor the senate hearings data is up to date (house hearings are fine). The latest data for both is **over a month old**. When will this be fixed?

**Comment by pll33** [comment]
@dwillis Just saw your [recent post](https://www.propublica.org/nerds/item/congress-api-update) about merging Sunlight responses into the ProPublica API. Any info for this though for the time being?

**Comment by dwillis** [comment]
@cynbreck we'll have the bills data updated tomorrow, and will check on the Senate hearings loader.

**Comment by pll33** [comment]
Thanks for the update!
