### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by joejordan** [propublica/sunlight-congress#551]
I noticed that there's a missing require in [test/test_helper.rb](https://github.com/propublica/congress/blob/master/test/test_helper.rb) that seems to indicate that there were unit tests present in the project at some point. Any idea what happened to them?

**Comment by dwillis** [comment]
No idea, @joejordan, but maybe @konklone does?

**Comment by konklone** [comment]
They're used in the functional tests, such as this one: https://github.com/propublica/congress/blob/master/test/functional/search_test.rb
