### ISSUE TITLE
Add ProPublica references / tone down Sunlight references

### ISSUE THREAD

**Issue by gregjd** [propublica/sunlight-congress#553]
I'm assuming this file: https://github.com/propublica/sunlight-congress/blob/gh-pages/index.md
is powering this page: https://sunlightlabs.github.io/congress/

And if so, you may wish to add references to ProPublica / say that ProPublica is managing it now. And also you might want to remove the references to the @sunlightlabs Twitter account and getting a Sunlight API key. And maybe add a link to what appears to be your [main Congress API site](https://propublica.github.io/congress-api-docs/)? Right now, people who visit this site may be confused, as they might be thinking, "I thought Sunlight isn't running the Congress API anymore... why does this site say they are?"

(I was going to submit a PR but I'm not quite sure what direction you have in mind for this site vs. the [other one](https://propublica.github.io/congress-api-docs/).)

**Comment by sethetter** [comment]
I second that, strongly. It's not clear what the plan is for the congress API, and the two projects seem to differ quite a bit, so making your intentions clear in this project would be very helpful!

**Comment by dwillis** [comment]
Here's our plan for the APIs: the Sunlight API will be shutting down on Aug. 31, 2017. More details here: https://www.propublica.org/nerds/item/congress-api-bill-subjects-personal-explanations-and-sunsetting-sunlight
