### ISSUE TITLE
Locate by lat/long returning incorrect NC district

### ISSUE THREAD

**Issue by gmassanek** [propublica/sunlight-congress#554]
## Thank you!!
First off, I could not be more thankful for this project and to all who make it run! Thank you!

## The Issue
I am using the /legislators/locate endpoint with lat/longs and have come across an example that is returning an incorrect district. I'm not sure if this is the best place to report, so if not, please point me in the right direction.

## Example
https://congress.api.sunlightfoundation.com/legislators/locate?latitude=35.5973832&longitude=-78.68441609999999 returns Representative Ted Budd of NC's 13th district, but should be returning George Holding of the 2nd district. I'm not sure if this is related to any recent re-drawing of the districts, but have verified a few ways that its incorrect.

I'm happy to help fix or report elsewhere if needed but I'd love to get this one fixed up!!

**Comment by dwillis** [comment]
@gmassanek Thanks for writing, and you're correct. As we will be deprecating the Sunlight Congress API this summer (see details [here](https://www.propublica.org/nerds/item/congress-api-update), we aren't going to be fixing this particular issue. We are recommending that developers who want to obtain congressional districts via lat/lng coordinates use the [Google Civic Information API](https://developers.google.com/civic-information/), which supports this feature.

**Comment by gmassanek** [comment]
Thanks for the prompt reply @dwillis. I'll check out with Google's api can give me. I was already doing address => lat/long => lookups so it looks like I might be able to skip a step.
